In [1]:
import numpy as np

In [32]:
a = np.array([1, 3, 5, 7, 9, 2, 4, 6, 8])

# 2D Arrays

In [13]:
b = np.array([[2, 4, 6, 8], [1, 3, 5, 7]])

In [14]:
b

array([[2, 4, 6, 8],
       [1, 3, 5, 7]])

# 3D Arrays

In [15]:
c = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [18]:
c.ndim #checking dimension

3

# Access Array Element

In [20]:
c[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
c[1]

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [27]:
c[1, 1]

array([4, 5, 6])

In [28]:
c[0, 1, 2]

6

In [29]:
c[1, -1]

array([4, 5, 6])

# Slicing Arrays

In [30]:
b

array([[2, 4, 6, 8],
       [1, 3, 5, 7]])

In [31]:
b[1 : 2]

array([[1, 3, 5, 7]])

In [33]:
a

array([1, 3, 5, 7, 9, 2, 4, 6, 8])

In [34]:
a[:2]

array([1, 3])

In [35]:
a[:-2]

array([1, 3, 5, 7, 9, 2, 4])

In [38]:
a[-3: -1]

array([4, 6])

In [39]:
a[1:5:2]

array([3, 7])

In [40]:
a[:: 2]

array([1, 5, 9, 4, 8])

In [41]:
b

array([[2, 4, 6, 8],
       [1, 3, 5, 7]])

In [42]:
b[0:2, 2] #from both elements retun index 2

array([6, 5])

# Data Types

In [43]:
a

array([1, 3, 5, 7, 9, 2, 4, 6, 8])

In [44]:
a.dtype

dtype('int32')

In [45]:
x = np.array(['apple', 'banana', 'cherry'])

In [46]:
x

array(['apple', 'banana', 'cherry'], dtype='<U6')

In [47]:
x.dtype

dtype('<U6')

In [54]:
np.array([2, 4, 6], dtype="S")

array([b'2', b'4', b'6'], dtype='|S1')

In [57]:
arr = np.array([2, 6, 7, 8], dtype='i4')

In [58]:
arr.dtype

dtype('int32')

In [61]:
b

array([[2, 4, 6, 8],
       [1, 3, 5, 7]])

In [62]:
newB = b.astype('f') #convert integer to float

In [63]:
newB

array([[2., 4., 6., 8.],
       [1., 3., 5., 7.]], dtype=float32)

# Copy and View

In [66]:
b

array([[2, 4, 6, 8],
       [1, 3, 5, 7]])

In [67]:
z = b.copy()

In [68]:
z

array([[2, 4, 6, 8],
       [1, 3, 5, 7]])

In [69]:
z[0, 0] = 1

In [70]:
z

array([[1, 4, 6, 8],
       [1, 3, 5, 7]])

In [74]:
 d = b.view()

In [75]:
d[0, 0] = 42

In [76]:
d

array([[42,  4,  6,  8],
       [ 1,  3,  5,  7]])

In [77]:
x.base
d.base

array([[42,  4,  6,  8],
       [ 1,  3,  5,  7]])

# Array Shape

In [78]:
b

array([[42,  4,  6,  8],
       [ 1,  3,  5,  7]])

In [79]:
b.shape

(2, 4)

In [81]:
x.shape

(3,)

In [84]:
arr = np.array([2, 4, 6], ndmin= 3)

In [85]:
arr

array([[[2, 4, 6]]])

In [88]:
arr.shape

(1, 1, 3)

In [89]:
b

array([[42,  4,  6,  8],
       [ 1,  3,  5,  7]])

In [90]:
b.reshape(4, 2)

array([[42,  4],
       [ 6,  8],
       [ 1,  3],
       [ 5,  7]])

In [91]:
b

array([[42,  4,  6,  8],
       [ 1,  3,  5,  7]])

In [93]:
for i in b:
    print(i)

[42  4  6  8]
[1 3 5 7]


In [94]:
for y in i:
    print(y)

1
3
5
7


# Array Join

In [98]:
arr1 = np.array([1, 3, 5, 7])

In [99]:
arr2 = np.array([2, 4, 6, 8])

In [100]:
new_arr =  np.concatenate((arr1, arr2))

In [101]:
new_arr

array([1, 3, 5, 7, 2, 4, 6, 8])

In [102]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

In [103]:
arr = np.concatenate((arr1, arr2), axis=1)

In [104]:
arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [107]:
arr = np.hstack((arr1, arr2))

In [108]:
arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [109]:
v_arr = np.vstack((arr1, arr2))

In [110]:
v_arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [111]:
a

7

In [112]:
a = np.array([1, 3, 5, 7, 9, 2, 4, 6, 8])

In [113]:
a

array([1, 3, 5, 7, 9, 2, 4, 6, 8])

In [116]:
newarr = np.array_split(a, 3)

In [117]:
newarr

[array([1, 3, 5]), array([7, 9, 2]), array([4, 6, 8])]

In [118]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

In [119]:
x = np.where(arr == 4)

In [120]:
x

(array([3, 5, 6], dtype=int64),)