In [1]:
import numpy as np

In [3]:
a = np.zeros((3,3,3))

In [4]:
a

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [5]:
np.ones((2,2,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [7]:
np.ones((2,2,4), dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [ ]:
np.full((2,2), 'hello', dtype="<U7

In [9]:
")

array([['hello', 'hello'],
       ['hello', 'hello']], dtype='<U7')

In [10]:
np.random.rand(10)

array([0.50448055, 0.69243339, 0.81188143, 0.21678396, 0.09663211,
       0.2451018 , 0.30642478, 0.14087956, 0.66805675, 0.46736756])

In [12]:
data = np.random.randint(5,10,(10,10))

In [13]:
data

Acccess of Numpy

array([[9, 5, 6, 7, 9, 9, 6, 6, 9, 5],
       [9, 7, 9, 9, 6, 5, 9, 8, 7, 9],
       [9, 6, 6, 6, 5, 7, 8, 5, 5, 6],
       [8, 7, 9, 8, 5, 6, 9, 8, 9, 6],
       [5, 6, 7, 8, 8, 5, 7, 7, 6, 9],
       [8, 9, 7, 5, 7, 7, 5, 8, 5, 8],
       [9, 7, 8, 5, 6, 7, 5, 5, 8, 5],
       [8, 8, 5, 9, 5, 6, 5, 9, 7, 7],
       [9, 6, 8, 6, 7, 6, 9, 8, 9, 7],
       [6, 7, 8, 7, 5, 7, 5, 7, 5, 8]])

# Access of numpy

In [15]:
data[4:8]

array([[5, 6, 7, 8, 8, 5, 7, 7, 6, 9],
       [8, 9, 7, 5, 7, 7, 5, 8, 5, 8],
       [9, 7, 8, 5, 6, 7, 5, 5, 8, 5],
       [8, 8, 5, 9, 5, 6, 5, 9, 7, 7]])

In [16]:
data[4:8, 4:6]

array([[8, 5],
       [7, 7],
       [6, 7],
       [5, 6]])

In [17]:
data[4:6, 4:6]

array([[8, 5],
       [7, 7]])

# Combine Data

In [18]:
data1 = np.random.randint(5,15, size=(5,3))

In [19]:
data2 = np.random.randint(5,15, size=(5,3))

In [20]:
np.hstack([data1, data2])

array([[ 6, 10,  7, 14, 14, 13],
       [ 7, 11,  5,  5,  8,  9],
       [12, 11, 12, 11, 12, 11],
       [14,  5, 14,  7,  9,  7],
       [ 6, 12,  5,  6,  6,  5]])

In [21]:
np.vstack([data1, data2])

array([[ 6, 10,  7],
       [ 7, 11,  5],
       [12, 11, 12],
       [14,  5, 14],
       [ 6, 12,  5],
       [14, 14, 13],
       [ 5,  8,  9],
       [11, 12, 11],
       [ 7,  9,  7],
       [ 6,  6,  5]])

In [22]:
np.concatenate([data1, data2], axis=1)

array([[ 6, 10,  7, 14, 14, 13],
       [ 7, 11,  5,  5,  8,  9],
       [12, 11, 12, 11, 12, 11],
       [14,  5, 14,  7,  9,  7],
       [ 6, 12,  5,  6,  6,  5]])

In [23]:
np.concatenate([data1, data2], axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [26]:
a1,a2 = np.hsplit(data,[5])

In [27]:
a1

array([[9, 5, 6, 7, 9],
       [9, 7, 9, 9, 6],
       [9, 6, 6, 6, 5],
       [8, 7, 9, 8, 5],
       [5, 6, 7, 8, 8],
       [8, 9, 7, 5, 7],
       [9, 7, 8, 5, 6],
       [8, 8, 5, 9, 5],
       [9, 6, 8, 6, 7],
       [6, 7, 8, 7, 5]])

# Shape Dimension

In [28]:
data.shape

(10, 10)

In [29]:
data.ndim

2

In [30]:
data.size

100

In [32]:
data.reshape(2,50)

array([[9, 5, 6, 7, 9, 9, 6, 6, 9, 5, 9, 7, 9, 9, 6, 5, 9, 8, 7, 9, 9, 6,
        6, 6, 5, 7, 8, 5, 5, 6, 8, 7, 9, 8, 5, 6, 9, 8, 9, 6, 5, 6, 7, 8,
        8, 5, 7, 7, 6, 9],
       [8, 9, 7, 5, 7, 7, 5, 8, 5, 8, 9, 7, 8, 5, 6, 7, 5, 5, 8, 5, 8, 8,
        5, 9, 5, 6, 5, 9, 7, 7, 9, 6, 8, 6, 7, 6, 9, 8, 9, 7, 6, 7, 8, 7,
        5, 7, 5, 7, 5, 8]])

In [33]:
d = np.array([1,2,3,4,5,6,7,8])

In [34]:
d.ndim

1

In [35]:
d.shape

(8,)

In [36]:
d.size

8

In [38]:
d.reshape(8,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

# Utility Function

In [39]:
np.sum(data)

698

In [40]:
np.sum(data, axis=1)

array([71, 78, 63, 75, 68, 69, 65, 69, 75, 65])

In [41]:
data

array([[9, 5, 6, 7, 9, 9, 6, 6, 9, 5],
       [9, 7, 9, 9, 6, 5, 9, 8, 7, 9],
       [9, 6, 6, 6, 5, 7, 8, 5, 5, 6],
       [8, 7, 9, 8, 5, 6, 9, 8, 9, 6],
       [5, 6, 7, 8, 8, 5, 7, 7, 6, 9],
       [8, 9, 7, 5, 7, 7, 5, 8, 5, 8],
       [9, 7, 8, 5, 6, 7, 5, 5, 8, 5],
       [8, 8, 5, 9, 5, 6, 5, 9, 7, 7],
       [9, 6, 8, 6, 7, 6, 9, 8, 9, 7],
       [6, 7, 8, 7, 5, 7, 5, 7, 5, 8]])

In [42]:
np.sin(data)

array([[ 0.41211849, -0.95892427, -0.2794155 ,  0.6569866 ,  0.41211849,
         0.41211849, -0.2794155 , -0.2794155 ,  0.41211849, -0.95892427],
       [ 0.41211849,  0.6569866 ,  0.41211849,  0.41211849, -0.2794155 ,
        -0.95892427,  0.41211849,  0.98935825,  0.6569866 ,  0.41211849],
       [ 0.41211849, -0.2794155 , -0.2794155 , -0.2794155 , -0.95892427,
         0.6569866 ,  0.98935825, -0.95892427, -0.95892427, -0.2794155 ],
       [ 0.98935825,  0.6569866 ,  0.41211849,  0.98935825, -0.95892427,
        -0.2794155 ,  0.41211849,  0.98935825,  0.41211849, -0.2794155 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.98935825,
        -0.95892427,  0.6569866 ,  0.6569866 , -0.2794155 ,  0.41211849],
       [ 0.98935825,  0.41211849,  0.6569866 , -0.95892427,  0.6569866 ,
         0.6569866 , -0.95892427,  0.98935825, -0.95892427,  0.98935825],
       [ 0.41211849,  0.6569866 ,  0.98935825, -0.95892427, -0.2794155 ,
         0.6569866 , -0.95892427, -0.95892427

In [43]:
data.T

array([[9, 9, 9, 8, 5, 8, 9, 8, 9, 6],
       [5, 7, 6, 7, 6, 9, 7, 8, 6, 7],
       [6, 9, 6, 9, 7, 7, 8, 5, 8, 8],
       [7, 9, 6, 8, 8, 5, 5, 9, 6, 7],
       [9, 6, 5, 5, 8, 7, 6, 5, 7, 5],
       [9, 5, 7, 6, 5, 7, 7, 6, 6, 7],
       [6, 9, 8, 9, 7, 5, 5, 5, 9, 5],
       [6, 8, 5, 8, 7, 8, 5, 9, 8, 7],
       [9, 7, 5, 9, 6, 5, 8, 7, 9, 5],
       [5, 9, 6, 6, 9, 8, 5, 7, 7, 8]])

In [44]:
data.mean(axis=1)

array([7.1, 7.8, 6.3, 7.5, 6.8, 6.9, 6.5, 6.9, 7.5, 6.5])

In [45]:
data.std(axis=1)

array([1.64012195, 1.4       , 1.26885775, 1.36014705, 1.2489996 ,
       1.37477271, 1.43178211, 1.5132746 , 1.20415946, 1.11803399])

# Broadcating

In [46]:
v = np.array([1,3,4,5,6])

In [47]:
s = 10

In [48]:
v + s

array([11, 13, 14, 15, 16])